  /// \file StandaloneRandomModule.h
/*
 *
 * StandaloneRandomModule.h header template automatically generated by a class generator
 * Creation date : sam. nov. 1 2014
 *
 * This file is part of DQM4HEP libraries.
 * 
 * DQM4HEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * DQM4HEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DQM4HEP.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */

#ifndef STANDALONERANDOMMODULE_H
#define STANDALONERANDOMMODULE_H

#include "dqm4hep/DQMStandaloneModule.h"

namespace dqm4hep
{

class DQMMonitorElement;

/** RandomModule class
 */ 
class StandaloneRandomModule : public DQMStandaloneModule
{
public:

	StandaloneRandomModule();
	~StandaloneRandomModule();

	StatusCode initModule();
	StatusCode startOfCycle();
	StatusCode endOfCycle();
	StatusCode readSettings(const TiXmlHandle xmlHandle);
	StatusCode process();
	StatusCode endModule();

protected:
	DQMMonitorElementPtr                        m_pTestElement;

	int            m_min;
	int            m_max;
}; 

} 

#endif  //  STANDALONERANDOMMODULE_H
