language: cpp

sudo: required

dist: trusty

compilers:
  - gcc
  - clang

os:
  - linux
  - osx
        
script:
  - ls /usr/lib/x86_64-linux-gnu/
  - ls /usr/lib/x86_64-linux-gnu/root5.34
  - mkdir build
  - cd build  
  - cmake -DBUILD_DQMVIZ=$BUILD_DQMVIZ -DINSTALL_DOC=$INSTALL_DOC -DDIM_GUI=OFF -DBUILD_DQM4ILC=OFF -DBUILD_EXAMPLES=$BUILD_EXAMPLES -DBUILD_EVB=$BUILD_EVB -DBUILD_HTTP=$BUILD_HTTP ..
  - make

addons:
  apt:
    sources:
    - sourceline: 'deb http://fr.archive.ubuntu.com/ubuntu trusty main universe'

env:
  global:
    - BUILD_DQMVIZ=OFF
    - INSTALL_DOC=OFF    
    - BUILD_EXAMPLES=OFF    
    - BUILD_EVB=OFF    
    - BUILD_HTTP=OFF

env:
  - BUILD_DQMVIZ=ON
  - INSTALL_DOC=ON
  - BUILD_EXAMPLES=ON
  - BUILD_EVB=ON
  - BUILD_HTTP=ON
  

matrix:
  include:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang
      
before_install:
  - sudo apt-get update -q
  - sudo apt-get install libqt4-dev qt4-qmake
  - sudo apt-get install libroot-gui-ged-dev libroot-hist5.34 libroot-hist-dev libroot-math-physics5.34 libroot-math-physics-dev libroot-core5.34 libroot-net-dev libroot-core-dev libroot-geom5.34 libroot-html-dev libroot-geom-dev libroot-io5.34 libroot-graf2d-gpad5.34 libroot-io-dev libroot-graf2d-gpad-dev libroot-graf2d-graf5.34 libroot-graf2d-graf-dev libroot-math-unuran-dev libroot-graf2d-postscript5.34 libroot-graf2d-postscript-dev libroot-graf3d-eve5.34 libroot-graf3d-eve-dev libroot-math-mathcore5.34 libroot-tmva-dev libroot-graf3d-g3d5.34 libroot-math-mathcore-dev libroot-tree5.34 libroot-graf3d-g3d-dev libroot-math-mathmore5.34 libroot-tree-dev libroot-graf3d-gl5.34 libroot-math-mathmore-dev libroot-graf3d-gl-dev libroot-math-matrix5.34 libroot-gui5.34 libroot-math-matrix-dev libroot-gui-dev libroot-gui-ged5.34 libroot-net5.34 root-plugin-io-xml root-plugin-geom-geompainter root-plugin-gui-qt root-plugin-graf2d-asimage root-plugin-gui-sessionviewer root-plugin-graf2d-qt root-plugin-hist-hbook root-plugin-graf2d-x11 root-plugin-hist-histpainter root-plugin-graf3d-x3d root-system root-system-bin root-system-common root-system-rootd 
  - sudo apt-get install liblog4cxx10 liblog4cxx10-dev
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libHistPainter.so.5.34 /usr/lib/x86_64-linux-gnu/libHistPainter.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libXMLIO.so.5.34 /usr/lib/x86_64-linux-gnu/libXMLIO.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libGeomPainter.so.5.34 /usr/lib/x86_64-linux-gnu/libGeomPainter.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libQtRoot.so.5.34 /usr/lib/x86_64-linux-gnu/libQtRoot.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libGQt.so.5.34 /usr/lib/x86_64-linux-gnu/libGQt.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libASImage.so.5.34 /usr/lib/x86_64-linux-gnu/libASImage.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libASImageGui.so.5.34 /usr/lib/x86_64-linux-gnu/libASImageGui.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libSessionViewer.so.5.34 /usr/lib/x86_64-linux-gnu/libSessionViewer.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libHistPainter.so.5.34 /usr/lib/x86_64-linux-gnu/libHistPainter.so

#before_script:
#  - svn co svn://svn.freehep.org/lcio/tags/v02-05 LCIO # install lcio just in case
#  - cd LCIO
#  - mkdir -p build
#  - cd build
#  - cmake ..
#  - make install
#  - cd ../../
#  - export LCIO_DIR=$PWD/LCIO
  
