language: cpp
dist: trusty
sudo: required

env:
  global:
    - DQM4hep_DOXYGEN_DOC=OFF
    - DQM4hep_COVERITY_SCAN=OFF
  matrix:
    - ROOT_VERSION=6.10.08
    - ROOT_VERSION=6.12.06
    - ROOT_VERSION=6.14.02

os: linux
compiler:
  - gcc
  - clang

matrix:
  fast_finish: true
  allow_failures:
  - os: osx
  include:
    - os: osx
      compiler: clang
      osx_image: xcode8.3 # default, osx 10.12
    - os: osx
      compiler: clang
      osx_image: xcode9.3 # osx 10.13
    - os: linux
      compiler: gcc
      env: ROOT_VERSION=6.10.08 DQM4hep_DOXYGEN_DOC=ON
    - os: linux
      compiler: gcc
      env: ROOT_VERSION=6.10.08 DQM4hep_DOXYGEN_DOC=OFF DQM4hep_COVERITY_SCAN=ON

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libmysqlclient-dev
      - doxygen
      - g++-4.9

script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" && "${CXX}" == "g++"  ]];
    then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90;
    fi
  - if [[ "${TRAVIS_EVENT_TYPE}" == "cron" && "${DQM4hep_COVERITY_SCAN}" == "ON" ]];
    then ./.travis-ci.d/coverity_scan.sh;
    elif [[ "${DQM4hep_COVERITY_SCAN}" == "OFF" ]] ./.travis-ci.d/compile_and_test.sh;
    fi

before_install:
  - ./.travis-ci.d/install_dependencies.sh
  - if [[ "${TRAVIS_OS_NAME}" == "osx"  ]];
    then brew install mysql;
    fi

after_success:
  - ./.travis-ci.d/deploy_doxygen.sh

# Don't send e-mail notifications
notifications:
  email:
    on_success: never
    on_failure: always