language: cpp

sudo: false

dist: trusty

compilers:
  - gcc
#  - clang

os:
  - linux
#  - osx
        
script:
  - make -j 4

addons:
  apt:
    sources:
    - sourceline: 'deb http://fr.archive.ubuntu.com/ubuntu trusty main universe'
    packages:
      - libqt4-dev
      - qt4-qmake
      - libboost-thread-dev
      - libboost-system-dev 
      - libboost-filesystem-dev
      - doxygen
      - liblog4cxx10
      - liblog4cxx10-dev
      
  coverity_scan:
    project:
      name: "apingault/dqm4hep"
      description: "Build submitted via Travis CI"
    notification_email: antoine.pingault@ugent.be
    build_command:   "make -j 4"
    branch_pattern: coverity_scan

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "VkdhwAMaxTEaHM7xJeQclNCzuC6x2f6mwepQZqJHtQ2krzlkLyJXRbmAtzolmUTBNUw82RA1TpbI3Dd3x5f3yJmQwKvjy0GuxokrHm2t9/MW8ScLGwCRBvXf0P3nPN8/ewThuqZGu+S/qTxinirghHWhJEiPGRmqGTM3sHKA9gxuwY9hQ6vVJzOa0QrMeu5Oegyw8pVIZFJ4AAcjr9alMK1Csxip20pSfBEID6RXivPG+LhzuBlKrVIrMz1DiGkxMw/dOM76GM/ZnrGCe0F0r7MskjZgZD0s3e2pp7i41cSgwNwKKpvYWEu536pxCRPhdEn261szkqeaMs3/a2Cx3dKTfvH3EjruAq3U/MkYTrliEFHm6lY7lJs6GOip0St9hWRUZR7ej66WcE+O3jgrq79nbNb7KvM66Yl0j7FRNWnOVc/r6Qz0jKy7hUTknaD18Oi3Puu1j96XGHOGKJLn2WW2/T0S4wrQVmHwtaeHT8ncEPUbtM7HVIZ0JshNujNR6AvmSqGMTB5Z1O+zROJWS8x4MRaqfM5mtP//zyVcl+HiKciPUuJKux1t+8r3i/ykWeTvFgWs9RSozaw3ciidtzoQohFZHiPNI3Ad8OxODw7t+YiwtvNqK7KDyCWgfE4vEjlPr6UC+k3hqWcVfTAPgxpvBIuU7D0pNMtWHpF8Cpc="

    - BUILD_DQMVIZ: OFF
    - INSTALL_DOC: OFF    
    - BUILD_EXAMPLES: OFF    
    - BUILD_EVB: OFF    
    - BUILD_HTTP: OFF
    - LD_LIBRARY_PATH: "/usr/lib/x86_64-linux-gnu/root5.34/:$LD_LIBRARY_PATH"
    - USE_COVERITY: false
    
  matrix:
    # - BUILD_DQMVIZ: OFF # Travis won't let root recompile with qt enable (build is too long)
    - INSTALL_DOC: ON
    - BUILD_EXAMPLES: ON
    - BUILD_EVB: ON
    - BUILD_HTTP: ON
      USE_MASTER: ON # Need master DQMCore branch for now
    - BUILD_DQMVIZ: OFF # Travis won't let root recompile with qt enable (build is too long)
      INSTALL_DOC: ON
      BUILD_EXAMPLES: ON
      BUILD_EVB: ON
      BUILD_HTTP: ON
      USE_MASTER: ON # Need master DQMCore branch for now
      USE_COVERITY: true
      
matrix:
  include:
#    - os: osx
#      compiler: clang
    - os: linux
      compiler: gcc
      
before_install:
  # Downlad&Unpack root binaries (Qt not enable -> No viz)
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd .. && wget https://root.cern.ch/download/root_v5.34.36.Linux-ubuntu14-x86_64-gcc4.8.tar.gz; fi 
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar -xf root_v5.34.36.Linux-ubuntu14-x86_64-gcc4.8.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then source root/bin/thisroot.sh; fi
  # Checking root config
  - root-config --version
  - cd -
  # Create build folder/run cmake here so we can build with coverity
  - mkdir -p build
  - cd build
  # Don't waste time with the doc when using coverity
  - if [ "$TRAVIS_BRANCH" == "coverity_scan" ];  then INSTALL_DOC=OFF; fi 
  # Don't run all the matrixes on coverity. Exiting gracefully so the build doesn't appear to have failed.
  - if [ "$TRAVIS_BRANCH" == "coverity_scan" ] && [ "$USE_COVERITY" = false ];  then echo "Running on coverity branch, Skipping this build"; exit 0; fi 
  - cmake -DBUILD_DQMVIZ=$BUILD_DQMVIZ -DINSTALL_DOC=$INSTALL_DOC -DDIM_GUI=OFF -DBUILD_DQM4ILC=OFF -DBUILD_EXAMPLES=$BUILD_EXAMPLES -DBUILD_EVB=$BUILD_EVB -DBUILD_HTTP=$BUILD_HTTP -DUSE_MASTER=$USE_MASTER ..
  
  # Coverity Scan
  # - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      


#before_script:
#  - svn co svn://svn.freehep.org/lcio/tags/v02-05 LCIO # install lcio just in case
#  - cd LCIO
#  - mkdir -p build
#  - cd build
#  - cmake ..
#  - make install
#  - cd ../../
#  - export LCIO_DIR=$PWD/LCIO
  
