language: cpp

sudo: required

dist: trusty

compilers:
  - gcc
  - clang

os:
  - linux
  - osx
        
script:
  - mkdir build
  - cd build  
  - cmake -DBUILD_DQMVIZ=$BUILD_DQMVIZ -DINSTALL_DOC=$INSTALL_DOC -DDIM_GUI=OFF -DBUILD_DQM4ILC=OFF -DBUILD_EXAMPLES=$BUILD_EXAMPLES -DBUILD_EVB=$BUILD_EVB -DBUILD_HTTP=$BUILD_HTTP ..
  - make

addons:
  apt:
    sources:
    - sourceline: 'deb http://fr.archive.ubuntu.com/ubuntu trusty main universe'

env:
  global:
    - BUILD_DQMVIZ=OFF
    - INSTALL_DOC=OFF    
    - BUILD_EXAMPLES=OFF    
    - BUILD_EVB=OFF    
    - BUILD_HTTP=OFF

env:
  - BUILD_DQMVIZ=ON
  - INSTALL_DOC=ON
  - BUILD_EXAMPLES=ON
  - BUILD_EVB=ON
  - BUILD_HTTP=ON
  

matrix:
  include:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang
      
before_install:
  - sudo apt-get update -q
  - sudo apt-get install libqt4-dev qt4-qmake
  - sudo apt-get install libroot-* root-plugin-*
  - sudo apt-get install liblog4cxx10 liblog4cxx10-dev

before_script:
  - svn co svn://svn.freehep.org/lcio/tags/v02-05 LCIO # install lcio just in case
  - cd LCIO
  - mkdir -p build
  - cd build
  - cmake ..
  - make install
  - cd ../../
  - export LCIO_DIR=$PWD/LCIO
  
