language: cpp
dist: trusty
sudo: required
os:
  - linux

script:
  - ./.travis-ci.d/compile_and_test.sh

before_install:
  - ./.travis-ci.d/install_dependencies.sh

compiler:
  - gcc
  - llvm

# Don't send e-mail notifications
notifications:
  email:
    on_success: never
    on_failure: always
