language: cpp
sudo: false
dist: trusty

compiler:
  - gcc
  - clang

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libmysqlclient-dev
      - doxygen
      - g++-4.9
      
before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
  - mkdir -p dependencies
  - cd dependencies
  - wget https://root.cern.ch/download/root_v6.10.08.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
  - tar -xf root_v6.10.08.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
  - source root/bin/thisroot.sh
  - root-config --version
  - cd ..
  - mkdir -p build
  - cd build
  - cmake -DDQM4HEP_USE_MASTER=ON -DDQM4HEP_DOXYGEN_DOC=OFF -DDQM4HEP_TESTING=ON -DDQM4HEP_WARNING_AS_ERROR=ON -DDQM4HEP_DEV_WARNINGS=ON ..

script:
  - make install -j 4
  
notifications:
  email:
    on_success: never
    on_failure: always

