/// \file AppEvent.cc
/*
 *
 * AppEvent.cc source template automatically generated by a class generator
 * Creation date : ven. sept. 5 2014
 *
 * This file is part of DQM4HEP libraries.
 * 
 * DQM4HEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * DQM4HEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DQM4HEP.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */

// -- dqm4hep headers
#include "dqm4hep/AppEvent.h"

namespace dqm4hep {

  namespace online {
    
    AppEvent::AppEvent(int t) :
      m_type(t) {
        /* nop */
    }
    
    //-------------------------------------------------------------------------------------------------
    
    AppEvent::~AppEvent() {
      /* nop */
    }
    
    //-------------------------------------------------------------------------------------------------
    
    int AppEvent::type() const {
      return m_type;
    }
    
    //-------------------------------------------------------------------------------------------------
        
    void AppEvent::setPriority(int p) {
      if(p > 100) {
        m_priority = 100;
      }
      else if(p < 0) {
        m_priority = 0;
      }
      else {
        m_priority = p;
      }
    }
    
    //-------------------------------------------------------------------------------------------------
    
    int AppEvent::priority() const {
      return m_priority;
    }

  }

}

