/// \file Server.cc
/*
 *
 * Server.cc source template automatically generated by a class generator
 * Creation date : sam. d�c. 3 2016
 *
 * This file is part of DQM4HEP libraries.
 *
 * DQM4HEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 *
 * DQM4HEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with DQM4HEP.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */

// -- dqm4hep headers
#include "dqm4hep/Server.h"

// -- std headers
#include <sys/utsname.h>
#include <unistd.h>
#include "dic.hxx"

namespace dqm4hep {

  namespace net {

    Server::Server(const std::string &name) :
        m_name(name),
        m_started(false),
        m_serverInfoHandler(this, m_name, "info", this, &Server::handleServerInfoRequest)
    {
      /* nop */
    }

    //-------------------------------------------------------------------------------------------------

    Server::~Server()
    {
      this->stop();
      this->clear();
    }

    //-------------------------------------------------------------------------------------------------

    const std::string &Server::getName() const
    {
      return m_name;
    }

    //-------------------------------------------------------------------------------------------------

    void Server::start()
    {
      if(m_started)
        return;

      for(auto iter = m_serviceMap.begin(), endIter = m_serviceMap.end() ; endIter != iter ; ++iter)
      {
        if(!iter->second->isServiceConnected())
          iter->second->connectService();
      }

      for(auto iter = m_requestHandlerMap.begin(), endIter = m_requestHandlerMap.end() ; endIter != iter ; ++iter)
      {
        if(!iter->second->isHandlingRequest())
          iter->second->startHandlingRequest();
      }

      std::string dimServerName(Server::getFullServerName(m_name));
      DimServer::start(const_cast<char*>(dimServerName.c_str()));
      m_started = true;
    }

    //-------------------------------------------------------------------------------------------------

    void Server::stop()
    {
      if(!m_started)
        return;

      for(auto iter = m_serviceMap.begin(), endIter = m_serviceMap.end() ; endIter != iter ; ++iter)
      {
        if(iter->second->isServiceConnected())
          iter->second->disconnectService();
      }

      for(auto iter = m_requestHandlerMap.begin(), endIter = m_requestHandlerMap.end() ; endIter != iter ; ++iter)
      {
        if(iter->second->isHandlingRequest())
          iter->second->stopHandlingRequest();
      }

      DimServer::stop();
      m_started = false;
    }

    //-------------------------------------------------------------------------------------------------

    bool Server::isRunning() const
    {
      return m_started;
    }

    //-------------------------------------------------------------------------------------------------

    void Server::clear()
    {
      for(auto iter = m_serviceMap.begin(), endIter = m_serviceMap.end() ; endIter != iter ; ++iter)
        delete iter->second;

      for(auto iter = m_requestHandlerMap.begin(), endIter = m_requestHandlerMap.end() ; endIter != iter ; ++iter)
        delete iter->second;

      m_serviceMap.clear();
      m_requestHandlerMap.clear();
      DimServer::stop();
      m_started = false;
    }

    //-------------------------------------------------------------------------------------------------

    bool Server::isServiceRegistered(const std::string &type, const std::string &name) const
    {
      return (m_serviceMap.find(BaseService::getFullServiceName(type, name)) != m_serviceMap.end());
    }

    //-------------------------------------------------------------------------------------------------

    bool Server::isRequestHandlerRegistered(const std::string &type, const std::string &name) const
    {
      return (m_requestHandlerMap.find(BaseRequestHandler::getFullRequestHandlerName(type, name)) != m_requestHandlerMap.end());
    }

    //-------------------------------------------------------------------------------------------------

    bool Server::isCommandHandlerRegistered(const std::string &type, const std::string &name) const
    {
      return (m_requestHandlerMap.find(BaseRequestHandler::getFullRequestHandlerName(type, name)) != m_commandHandlerMap.end());
    }

    //-------------------------------------------------------------------------------------------------

    void Server::startService(const std::string &type, const std::string &name)
    {
      BaseService *pService = this->getService(type, name);

      if(nullptr != pService && !pService->isServiceConnected())
        pService->connectService();
    }

    //-------------------------------------------------------------------------------------------------

    void Server::stopService(const std::string &type, const std::string &name)
    {
      BaseService *pService = this->getService(type, name);

      if(nullptr != pService && pService->isServiceConnected())
        pService->disconnectService();
    }

    //-------------------------------------------------------------------------------------------------

    void Server::startRequestHandler(const std::string &type, const std::string &name)
    {
      BaseRequestHandler *pRequestHandler = this->getRequestHandler(type, name);

      if(nullptr != pRequestHandler && !pRequestHandler->isHandlingRequest())
        pRequestHandler->startHandlingRequest();
    }

    //-------------------------------------------------------------------------------------------------

    void Server::stopRequestHandler(const std::string &type, const std::string &name)
    {
      BaseRequestHandler *pRequestHandler = this->getRequestHandler(type, name);

      if(nullptr != pRequestHandler && pRequestHandler->isHandlingRequest())
        pRequestHandler->stopHandlingRequest();
    }

    //-------------------------------------------------------------------------------------------------

    void Server::startCommandHandler(const std::string &type, const std::string &name)
    {
      BaseRequestHandler *pCommandHandler = this->getCommandHandler(type, name);

      if(nullptr != pCommandHandler && !pCommandHandler->isHandlingRequest())
        pCommandHandler->startHandlingRequest();
    }

    //-------------------------------------------------------------------------------------------------

    void Server::stopCommandHandler(const std::string &type, const std::string &name)
    {
      BaseRequestHandler *pCommandHandler = this->getCommandHandler(type, name);

      if(nullptr != pCommandHandler && pCommandHandler->isHandlingRequest())
        pCommandHandler->stopHandlingRequest();
    }

    //-------------------------------------------------------------------------------------------------

    BaseService *Server::getService(const std::string &type, const std::string &name) const
    {
      auto findIter = m_serviceMap.find(BaseService::getFullServiceName(type, name));
      return (findIter == m_serviceMap.end() ? nullptr : findIter->second);
    }

    //-------------------------------------------------------------------------------------------------

    BaseRequestHandler *Server::getRequestHandler(const std::string &type, const std::string &name) const
    {
      auto findIter = m_requestHandlerMap.find(BaseRequestHandler::getFullRequestHandlerName(type, name));
      return (findIter == m_requestHandlerMap.end() ? nullptr : findIter->second);
    }

    //-------------------------------------------------------------------------------------------------

    BaseRequestHandler *Server::getCommandHandler(const std::string &type, const std::string &name) const
    {
      auto findIter = m_commandHandlerMap.find(BaseRequestHandler::getFullRequestHandlerName(type, name));
      return (findIter == m_commandHandlerMap.end() ? nullptr : findIter->second);
    }

    //-------------------------------------------------------------------------------------------------

    std::string Server::getDnsNode()
    {
      char *pDnsNode = DimServer::getDnsNode();

      if(pDnsNode)
        return pDnsNode;

      pDnsNode = getenv("DIM_DNS_NODE");
      return (pDnsNode ? pDnsNode : "");
    }

    //-------------------------------------------------------------------------------------------------

    int Server::getDnsPort()
    {
      return DimServer::getDnsPort();
    }

    //-------------------------------------------------------------------------------------------------

    std::string Server::getFullServerName(const std::string &serverName)
    {
      return ("dqm4hep/" + serverName);
    }

    //-------------------------------------------------------------------------------------------------

    std::vector<std::string> Server::getRunningServers()
    {
      std::vector<std::string> runningServers;

      DimBrowser browser;
      browser.getServers();
      char *pServer, *pNode;

      while(browser.getNextServer(pServer, pNode))
      {
        std::string server(pServer);

        if(server.substr(0, std::string("dqm4hep/").size()) == "dqm4hep/")
          runningServers.push_back(server.substr(std::string("dqm4hep/").size()));
      }

      return runningServers;
    }

    //-------------------------------------------------------------------------------------------------

    bool Server::isServerRunning(const std::string &serverName)
    {
      DimBrowser browser;
      browser.getServers();
      char *pServer, *pNode;

      while(browser.getNextServer(pServer, pNode))
      {
        std::string server(pServer);

        if(server.substr(0, std::string("dqm4hep/").size()) == "dqm4hep/")
        {
          std::string realServerName(server.substr(std::string("dqm4hep/").size()));

          if(realServerName == serverName)
            return true;
        }
      }

      return false;
    }

    //-------------------------------------------------------------------------------------------------

    void Server::handleServerInfoRequest(const Json::Value &/*request*/, Json::Value &response)
    {
      Json::Value serverInfo;
      serverInfo["name"] = m_name;
      response["server"] = serverInfo;

      // uname
      struct utsname unameStruct;
      uname(&unameStruct);

      // host name
      char host[256];
      gethostname(host, 256);

      Json::Value hostInfo;
      hostInfo["name"] = host;
      hostInfo["system"] = unameStruct.sysname;
      hostInfo["node"] = unameStruct.nodename;
      hostInfo["release"] = unameStruct.release;
      hostInfo["version"] = unameStruct.version;
      hostInfo["machine"] = unameStruct.machine;
      response["host"] = hostInfo;

      Json::Value servicesInfo;
      unsigned int index(0);

      for(auto iter = m_serviceMap.begin(), endIter = m_serviceMap.end() ; endIter != iter ; ++iter)
      {
        const std::string &type(iter->second->getType());
        const std::string &name(iter->second->getName());
        const std::string &fullName(iter->second->getFullName());

        Json::Value serviceInfo;
        serviceInfo["type"] = type;
        serviceInfo["name"] = name;
        serviceInfo["fullName"] = fullName;
        servicesInfo[index] = serviceInfo;

        ++index;
      }

      response["services"] = servicesInfo;

      Json::Value requestHandlersInfo;
      index = 0;

      for(auto iter = m_requestHandlerMap.begin(), endIter = m_requestHandlerMap.end() ; endIter != iter ; ++iter)
      {
        const std::string &type(iter->second->getType());
        const std::string &name(iter->second->getName());

        Json::Value requestHandlerInfo;
        requestHandlerInfo["type"] = type;
        requestHandlerInfo["name"] = name;
        requestHandlersInfo[index] = requestHandlerInfo;

        ++index;
      }

      response["requestHandlers"] = requestHandlersInfo;
    }

    //-------------------------------------------------------------------------------------------------

    bool Server::serviceAlreadyRunning(const std::string &type, const std::string &name)
    {
      DimBrowser browser;
      const std::string fullServiceName(BaseService::getFullServiceName(type, name));
      int nServices = browser.getServices(fullServiceName.c_str());

      if(nServices == 0)
        return false;

      int serviceType;
      char *serviceName, *format;

      while(1)
      {
        serviceType = browser.getNextService(serviceName, format);

        if(serviceType == 0)
          break;

        if(serviceType == DimSERVICE)
          return true;
      }

      return false;
    }

    //-------------------------------------------------------------------------------------------------

    bool Server::requestHandlerAlreadyRunning(const std::string &type, const std::string &name)
    {
      DimBrowser browser;
      const std::string fullServiceName(BaseRequestHandler::getFullRequestHandlerName(type, name));
      int nServices = browser.getServices(fullServiceName.c_str());

      if(nServices == 0)
        return false;

      int serviceType;
      char *serviceName, *format;

      while(1)
      {
        serviceType = browser.getNextService(serviceName, format);

        if(serviceType == 0)
          break;

        if(serviceType == DimRPC)
          return true;
      }

      return false;
    }

    //-------------------------------------------------------------------------------------------------

    bool Server::commandHandlerAlreadyRunning(const std::string &type, const std::string &name)
    {
      DimBrowser browser;
      const std::string fullServiceName(BaseRequestHandler::getFullRequestHandlerName(type, name));
      int nServices = browser.getServices(fullServiceName.c_str());

      if(nServices == 0)
        return false;

      int serviceType;
      char *serviceName, *format;

      while(1)
      {
        serviceType = browser.getNextService(serviceName, format);

        if(serviceType == 0)
          break;

        if(serviceType == DimCOMMAND)
          return true;
      }

      return false;
    }

  }

}
