#! /bin/bash
# This script configures MySQL for DQM4HEP from scratch
# Create the db, the users, and the basic tables


echo "Configuration of MySQL database for DQM4HEP (admin script)"
echo "Please follow instructions. Values in [] are defaults if nothing answered"
echo "This script requires to have the mysql root password on the host you want to setup your db"
echo ""

LOCALHOST=`hostname`

# Ask which MySQL server to use

read -p "Please enter MySQL server host name [localhost] : " DQM4HEP_DB_MYSQL_HOST

if [ "$DQM4HEP_DB_MYSQL_HOST" = "" ]; 
	then DQM4HEP_DB_MYSQL_HOST="localhost"; 
fi

# Test if a root password is defined
PASSWORD=""
mysql -h $DQM4HEP_DB_MYSQL_HOST -u root -e "exit" > /dev/null 2>&1

if [ "$?" = "0" ]; 
then 
  echo "No password is defined yet to access MySQL server with user 'root' on $DQM4HEP_DB_MYSQL_HOST"
  stty -echo
  read -p "Please enter new root password for mysql [leave blank]: " PASSWORD
  stty echo
  echo

  if [ "$PASSWORD" != "" ];
  then
  
    stty -echo
    read -p "Please enter again: " PASSWORD2
    stty echo
    echo
    
    if [ "$PASSWORD" != "$PASSWORD2" ]; 
    then
      echo "Mismatch!"
      exit 1
    fi
    
    /usr/bin/mysqladmin -h $DQM4HEP_DB_MYSQL_HOST -u root password "$PWD"
    
    echo "Password updated"
    PASSWORD="-p$PASSWORD"
    
    # remove empty entries as well
    mysql -h $DQM4HEP_DB_MYSQL_HOST -u root $PASSWORD -e "DELETE FROM mysql.user WHERE User = ''; \
      FLUSH PRIVILEGES;"
  else
    echo "Root password left blank"
  fi

else

  stty -echo
  read -p "Please enter root password for mysql : " PASSWORD
  stty echo
  echo
  
  if [ "$PASSWORD" != "" ]; then
    PASSWORD="-p$PASSWORD"
  fi

fi

# try connection
mysql -h $DQM4HEP_DB_MYSQL_HOST -u root $PASSWORD -e "exit"
if [ "$?" != "0" ]; then 
  echo "Connection failed"
  exit 1
fi


echo "Database creation - existing databases will NOT be destroyed"

read -p "Please enter the database name to create [DQM4HEP] : " DQM4HEP_DB_MYSQL_DB
if [ "$DQM4HEP_DB_MYSQL_DB" = "" ]; then  DQM4HEP_DB_MYSQL_DB=DQM4HEP; fi
mysql -h $DQM4HEP_DB_MYSQL_HOST -u root $PASSWORD -e "CREATE DATABASE IF NOT EXISTS $DQM4HEP_DB_MYSQL_DB ;"

if [ "$?" != "0" ]; then 
  echo "Couldn't create database !"
  exit 1
fi

echo "DQM4HEP MySQL database was succesfully created"
exit 0


