#! /bin/bash
# This script configures MySQL for DQM4HEP from scratch
# Create the db, the users, and the basic tables


echo "This script create a new mysql user and setup privileges"
echo "Please follow instructions. Values in [] are defaults if nothing answered"
echo "This script requires to have the mysql root password on the host you want to create the user"
echo ""

LOCALHOST=`hostname`

# Ask which MySQL server to use

read -p "Please enter MySQL server host name [localhost] : " DQM4HEP_DB_MYSQL_HOST

if [ "$DQM4HEP_DB_MYSQL_HOST" = "" ]; 
	then DQM4HEP_DB_MYSQL_HOST="localhost"; 
fi

# Test if a root password is defined
PASSWORD=""
mysql -h $DQM4HEP_DB_MYSQL_HOST -u root -e "exit" > /dev/null 2>&1

if [ "$?" = "0" ]; 
then 
  echo "No password is defined yet to access MySQL server with user 'root' on $DQM4HEP_DB_MYSQL_HOST"
  stty -echo
  read -p "Please enter new root password for mysql [leave blank]: " PASSWORD
  stty echo
  echo

  if [ "$PASSWORD" != "" ];
  then
  
    stty -echo
    read -p "Please enter again: " PASSWORD2
    stty echo
    echo
    
    if [ "$PASSWORD" != "$PASSWORD2" ]; 
    then
      echo "Mismatch!"
      exit 1
    fi
    
    /usr/bin/mysqladmin -h $DQM4HEP_DB_MYSQL_HOST -u root password "$PWD"
    
    echo "Password updated"
    PASSWORD="-p$PASSWORD"
    
    # remove empty entries as well
    mysql -h $DQM4HEP_DB_MYSQL_HOST -u root $PASSWORD -e "DELETE FROM mysql.user WHERE User = ''; \
      FLUSH PRIVILEGES;"
  else
    echo "Root password left blank"
  fi

else

  stty -echo
  read -p "Please enter root password for mysql : " PASSWORD
  stty echo
  echo
  
  if [ "$PASSWORD" != "" ]; then
    PASSWORD="-p$PASSWORD"
  fi

fi

# try connection
mysql -h $DQM4HEP_DB_MYSQL_HOST -u root $PASSWORD -e "exit"
if [ "$?" != "0" ]; then 
  echo "Connection failed"
  exit 1
fi

# Get the db name and check for existence
read -p "Please enter the database name in use [DQM4HEP] : " DQM4HEP_DB_MYSQL_DB
if [ "$DQM4HEP_DB_MYSQL_DB" = "" ]; then  DQM4HEP_DB_MYSQL_DB=DQM4HEP; fi

mysql -h $DQM4HEP_DB_MYSQL_HOST -u root $PASSWORD -e "USE $DQM4HEP_DB_MYSQL_DB"
if [ "$?" != "0" ]; then 
  echo "Database '$DQM4HEP_DB_MYSQL_DB' doesn't exist !"
  exit 1
fi

# Create account
read -p "Please enter a username (can't be 'DQM4HEP') : " DQM4HEP_DB_MYSQL_USER 

if [ "$DQM4HEP_DB_MYSQL_USER" = "DQM4HEP" ]
then
  echo "Username can not be DQM4HEP ! Exiting"
  exit 1  
fi

if [ "$DQM4HEP_DB_MYSQL_USER" = "" ]
then  
    echo "No username specified ! Exiting"
    exit 1
fi

# Get the new user password
stty -echo
read -p "Please enter your password : " DQM4HEP_DB_MYSQL_PWD
stty echo

if [ "$DQM4HEP_DB_MYSQL_PWD" = "" ]
then  
  echo "Can not create a mysql without password (not allowed by DQM4HEP) !"
  exit 1
fi

mysql -h $DQM4HEP_DB_MYSQL_HOST -u root $PASSWORD -e "CREATE USER IF NOT EXISTS DQM4HEP"
if [ "$?" != "0" ]; then 
  echo "Couldn't create DQM4HEP user !"
  exit 1
fi

HERE=`hostname -f`

mysql -h $DQM4HEP_DB_MYSQL_HOST -u root $PASSWORD -e "
  CREATE USER IF NOT EXISTS \"DQM4HEP\"@\"%\",
                            \"DQM4HEP\"@\"localhost\",
                            \"DQM4HEP\"@\"$HERE\";"

mysql -h $DQM4HEP_DB_MYSQL_HOST -u root $PASSWORD -e "
  CREATE USER \"$DQM4HEP_DB_MYSQL_USER\"@\"%\" IDENTIFIED BY \"$DQM4HEP_DB_MYSQL_PWD\",
              \"$DQM4HEP_DB_MYSQL_USER\"@\"localhost\" IDENTIFIED BY \"$DQM4HEP_DB_MYSQL_PWD\",
              \"$DQM4HEP_DB_MYSQL_USER\"@\"$HERE\" IDENTIFIED BY \"$DQM4HEP_DB_MYSQL_PWD\";"

if [ "$?" != "0" ]; then 
  echo "Couldn't create user (username = '$DQM4HEP_DB_MYSQL_USER')!"
  exit 1
fi

mysql -h $DQM4HEP_DB_MYSQL_HOST -u root $PASSWORD -e "
  grant all privileges on $DQM4HEP_DB_MYSQL_DB.* to \"$DQM4HEP_DB_MYSQL_USER\"@\"%\";
  grant all privileges on $DQM4HEP_DB_MYSQL_DB.* to \"$DQM4HEP_DB_MYSQL_USER\"@\"localhost\";
  grant all privileges on $DQM4HEP_DB_MYSQL_DB.* to \"$DQM4HEP_DB_MYSQL_USER\"@\"$HERE\";
  grant select on $DQM4HEP_DB_MYSQL_DB.* to \"DQM4HEP\"@\"%\";
  grant select on $DQM4HEP_DB_MYSQL_DB.* to \"DQM4HEP\"@\"localhost\";
  grant select on $DQM4HEP_DB_MYSQL_DB.* to \"DQM4HEP\"@\"$HERE\";
"

if [ "$?" != "0" ]; then 
  echo "Couldn't grant access to db !"
  exit 1
fi

echo "DQM4HEP MySQL users were succesfully created"
exit 0


