#! /bin/bash
# This script configures MySQL for DQM4HEP from scratch
# Create the db, the users, and the basic tables


echo "Configuration of MySQL database for DQM4HEP"
echo "Please follow instructions. Values in [] are defaults if nothing answered"
echo ""

LOCALHOST=`hostname`

# Ask which MySQL server to use

read -p "Please enter MySQL server host name [localhost] : " DQM4HEP_DB_MYSQL_HOST

if [ "$DQM4HEP_DB_MYSQL_HOST" = "" ]; 
	then DQM4HEP_DB_MYSQL_HOST="localhost"; 
fi

# Test if a root password is defined
PASSWORD=""
mysql -h $DQM4HEP_DB_MYSQL_HOST -u root -e "exit" > /dev/null 2>&1

if [ "$?" = "0" ]; 
then 
  echo "No password is defined yet to access MySQL server with user 'root' on $DQM4HEP_DB_MYSQL_HOST"
  stty -echo
  read -p "Please enter new root password for mysql [leave blank]: " PASSWORD
  stty echo
  echo

  if [ "$PASSWORD" != "" ];
  then
  
    stty -echo
    read -p "Please enter again: " PASSWORD2
    stty echo
    echo
    
    if [ "$PASSWORD" != "$PASSWORD2" ]; 
    then
      echo "Mismatch!"
      exit 1
    fi
    
    /usr/bin/mysqladmin -h $DQM4HEP_DB_MYSQL_HOST -u root password "$PWD"
    
    echo "Password updated"
    PASSWORD="-p$PASSWORD"
    
    # remove empty entries as well
    mysql -h $DQM4HEP_DB_MYSQL_HOST -u root $PASSWORD -e "DELETE FROM mysql.user WHERE User = ''; \
      FLUSH PRIVILEGES;"
  else
    echo "Root password left blank"
  fi

else

  stty -echo
  read -p "Please enter root password for mysql : " PASSWORD
  stty echo
  echo
  
  if [ "$PASSWORD" != "" ]; then
    PASSWORD="-p$PASSWORD"
  fi

fi

# try connection
mysql -h $DQM4HEP_DB_MYSQL_HOST -u root $PASSWORD -e "exit"
if [ "$?" != "0" ]; then 
  echo "Connection failed"
  exit 1
fi


echo "Database creation - existing databases will NOT be destroyed"
mysql -h $DQM4HEP_DB_MYSQL_HOST -u root $PASSWORD -e "CREATE DATABASE DQM4HEP ;"

# Create account
read -p "Please enter a username and password to be created to access DQM4HEP databases (space separated) [DQM4HEP DQM4HEP] : " DQM4HEP_DB_MYSQL_USER DQM4HEP_DB_MYSQL_PWD
if [ "$DQM4HEP_DB_MYSQL_USER" = "" ]; then  DQM4HEP_DB_MYSQL_USER=DQM4HEP; fi
if [ "$DQM4HEP_DB_MYSQL_PWD" = "" ]; then  DQM4HEP_DB_MYSQL_PWD=DQM4HEP; fi

HERE=`hostname -f`

mysql -h $DQM4HEP_DB_MYSQL_HOST -u root $PASSWORD -e "
  grant all privileges on DQM4HEP.* to \"$DQM4HEP_DB_MYSQL_USER\"@\"%\" identified by \"$DQM4HEP_DB_MYSQL_PWD\";
  grant all privileges on DQM4HEP.* to \"$DQM4HEP_DB_MYSQL_USER\"@\"localhost\" identified by \"$DQM4HEP_DB_MYSQL_PWD\";
  grant all privileges on DQM4HEP.* to \"$DQM4HEP_DB_MYSQL_USER\"@\"$HERE\" identified by \"$DQM4HEP_DB_MYSQL_PWD\";
"

echo "Creating configuration tables"

mysql DQM4HEP -u $DQM4HEP_DB_MYSQL_USER -p$DQM4HEP_DB_MYSQL_PWD -h $DQM4HEP_DB_MYSQL_HOST -e \
"
CREATE TABLE IF NOT EXISTS CONFIG_FILES (
	FILE_NAME VARCHAR(255) NOT NULL PRIMARY KEY,
	DESCRIPTION LONGTEXT,
	CONTENTS LONGTEXT NOT NULL
);
"

echo "DQM4HEP MySQL server accounts and database were succesfully created"







