/// \file DQMFileHandlerFactory.h
/*
 *
 * DQMFileHandlerFactory.h header template automatically generated by a class generator
 * Creation date : lun. janv. 11 2016
 *
 * This file is part of DQM4HRP libraries.
 * 
 * DQM4HRP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * DQM4HRP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DQM4HRP.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#ifndef DQM4HEP_FILEHANDLERFACTORY_H
#define DQM4HEP_FILEHANDLERFACTORY_H

// -- std headers
#include <string>

namespace dqm4hep {

  namespace core {

    class FileHandler;

    /** FileHandlerFactory class
     */
    class FileHandlerFactory
    {
    public:
      /** Constructor
       */
      FileHandlerFactory();

      /** Create a file handler with target type
       */
      FileHandler *createFileHandler(const std::string &fileHandlerType) const;
    };

  }

} 

#endif  //  DQM4HEP_FILEHANDLERFACTORY_H
